### ISSUE TITLE
hey can you post a Releases with all the modules?

### ISSUE THREAD

**Issue by alonalibarmn** [Nukestye/Zodiac#44]

**Comment by Nukestye** [comment]
You want the models used in the project listed? You can check them in [package.json](https://github.com/Nukestye/Zodiac/blob/master/package.json). But I will make sure next release to list new modules used with the previous ones.

**Comment by alonalibarmn** [comment]
not the listed just all the models in file

**Comment by Nukestye** [comment]
I don’t understand what you mean? All the modules used are in the file mentioned above. You can do `npm install` to install all the modules/dependencies. If you mean modules as the ones I make then I’ll have a look through and list them.

**Comment by alonalibarmn** [comment]
i mean like send the all the modules 
like send the folder node_modules

**Comment by Nukestye** [comment]
You can get the node modules folder by doing `npm install`. Also all the modules that are **used** are listed in  [package.json](https://github.com/Nukestye/Zodiac/blob/master/package.json) and [package-lock.json](https://github.com/Nukestye/Zodiac/blob/master/package-lock.json). As long as you have those two files and run the command, you will get a node module folder.

**Comment by Nukestye** [comment]
The reason I don't include the node_modules folder is because when committing to this repository their will be hundreds of random files that I haven't changed but were added by node, which makes it hard to proof check changes I've made.

You can easily get the node modules folder by having the two files mentioned above ([package.json](https://github.com/Nukestye/Zodiac/blob/master/package.json) and [package-lock.json](https://github.com/Nukestye/Zodiac/blob/master/package-lock.json)) and using the command: `npm install` in the terminal, where it will install all the dependencies listed in the files.

**Comment by Nukestye** [comment]
Issue closed due to inactivity.
